"""FOIA Automation — sunlight is the best disinfectant.

Generates, tracks, and follows up on Freedom of Information Act
requests to federal and state environmental agencies.

When Raíz finds a facility with violations but no inspection
records, or a permit with no public documentation, it generates
a FOIA request, tracks the response deadline, and flags
stonewalling when agencies don't respond within the legally
required timeframe.

Federal FOIA: 20 business days to respond (can extend 10 more).
State FOIA: varies by state (typically 5-30 days).

Raíz doesn't file the requests itself — it generates the letter,
tells the community member where to send it, and tracks the clock.
The human signs the letter. Raíz remembers the deadline.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class FoiaRequest:
    """A FOIA request generated by Raíz."""
    request_id: str
    target_agency: str
    target_address: str
    target_email: str = ""
    subject: str = ""
    records_requested: list[str] = field(default_factory=list)
    facility_name: str = ""
    facility_id: str = ""
    date_range: str = ""
    generated_date: str = ""
    filed_date: str = ""
    response_deadline: str = ""
    status: str = "draft"  # draft, filed, acknowledged, responded, overdue, appealed
    response_summary: str = ""
    fee_waiver_requested: bool = True

    @property
    def is_overdue(self) -> bool:
        if not self.response_deadline:
            return False
        try:
            deadline = datetime.strptime(self.response_deadline, "%Y-%m-%d")
            return datetime.now() > deadline and self.status not in ("responded",)
        except ValueError:
            return False

    @property
    def days_until_deadline(self) -> int:
        if not self.response_deadline:
            return -1
        try:
            deadline = datetime.strptime(self.response_deadline, "%Y-%m-%d")
            return (deadline - datetime.now()).days
        except ValueError:
            return -1


# State environmental agencies and their FOIA contacts
STATE_AGENCIES = {
    "IL": {
        "name": "Illinois Environmental Protection Agency",
        "foia_address": "FOIA Officer, Illinois EPA, 1021 North Grand Avenue East, Springfield, IL 62702",
        "foia_email": "epa.foia@illinois.gov",
        "response_days": 5,
    },
    "CA": {
        "name": "California Department of Toxic Substances Control",
        "foia_address": "Public Records Act Coordinator, DTSC, P.O. Box 806, Sacramento, CA 95812",
        "foia_email": "dtscpra@dtsc.ca.gov",
        "response_days": 10,
    },
    "TX": {
        "name": "Texas Commission on Environmental Quality",
        "foia_address": "Public Information Officer, TCEQ, P.O. Box 13087, Austin, TX 78711",
        "foia_email": "pia@tceq.texas.gov",
        "response_days": 10,
    },
    "NY": {
        "name": "New York State Department of Environmental Conservation",
        "foia_address": "Records Access Officer, NYSDEC, 625 Broadway, Albany, NY 12233",
        "foia_email": "foil@dec.ny.gov",
        "response_days": 5,
    },
    "OH": {
        "name": "Ohio Environmental Protection Agency",
        "foia_address": "Public Records Manager, Ohio EPA, P.O. Box 1049, Columbus, OH 43216",
        "foia_email": "publicrecords@epa.ohio.gov",
        "response_days": 10,
    },
}

FEDERAL_EPA = {
    "name": "U.S. Environmental Protection Agency",
    "foia_address": "National FOIA Office, U.S. EPA, 1200 Pennsylvania Avenue NW, Washington, DC 20460",
    "foia_email": "hq.foia@epa.gov",
    "response_days": 20,
}


class FoiaGenerator:
    """Generate and track FOIA requests."""

    def __init__(self) -> None:
        self._requests: list[FoiaRequest] = []
        self._counter = 0

    def generate_inspection_request(
        self,
        facility_name: str,
        facility_id: str,
        state: str,
        requester_name: str = "[YOUR NAME]",
        requester_address: str = "[YOUR ADDRESS]",
    ) -> FoiaRequest:
        """Generate a FOIA request for facility inspection records."""
        agency = STATE_AGENCIES.get(state, FEDERAL_EPA)
        self._counter += 1
        request_id = f"RAIZ-FOIA-{self._counter:04d}"

        now = datetime.now()
        response_days = agency.get("response_days", 20)
        deadline = now + timedelta(days=response_days)

        request = FoiaRequest(
            request_id=request_id,
            target_agency=agency["name"],
            target_address=agency["foia_address"],
            target_email=agency.get("foia_email", ""),
            subject=f"FOIA Request — Inspection and Compliance Records for {facility_name}",
            records_requested=[
                f"All inspection reports for {facility_name} (ID: {facility_id}) for the past 5 years",
                "All notices of violation issued to this facility",
                "All consent orders, consent decrees, or compliance schedules",
                "All penalty assessments and penalty payment records",
                "All compliance monitoring reports submitted by the facility",
                "All citizen complaints received regarding this facility",
                "All correspondence between the agency and the facility regarding compliance",
            ],
            facility_name=facility_name,
            facility_id=facility_id,
            date_range=f"{now.year - 5}-01-01 to present",
            generated_date=now.strftime("%Y-%m-%d"),
            response_deadline=deadline.strftime("%Y-%m-%d"),
            status="draft",
        )
        self._requests.append(request)
        return request

    def generate_permit_request(
        self,
        permit_id: str,
        facility_name: str,
        state: str,
    ) -> FoiaRequest:
        """Generate a FOIA request for permit application documents."""
        agency = STATE_AGENCIES.get(state, FEDERAL_EPA)
        self._counter += 1
        request_id = f"RAIZ-FOIA-{self._counter:04d}"

        now = datetime.now()
        response_days = agency.get("response_days", 20)

        request = FoiaRequest(
            request_id=request_id,
            target_agency=agency["name"],
            target_address=agency["foia_address"],
            target_email=agency.get("foia_email", ""),
            subject=f"FOIA Request — Permit Application {permit_id} for {facility_name}",
            records_requested=[
                f"Complete permit application for {permit_id}",
                "All environmental impact assessments or analyses submitted",
                "All public comments received regarding this application",
                "Agency review notes and internal correspondence regarding this application",
                "Any air dispersion modeling or water quality modeling submitted",
                "All emission or discharge estimates provided by the applicant",
            ],
            facility_name=facility_name,
            facility_id=permit_id,
            generated_date=now.strftime("%Y-%m-%d"),
            response_deadline=(now + timedelta(days=response_days)).strftime("%Y-%m-%d"),
            status="draft",
        )
        self._requests.append(request)
        return request

    def format_letter(self, request: FoiaRequest, requester_name: str = "[YOUR NAME]", requester_address: str = "[YOUR ADDRESS]") -> str:
        """Format a FOIA request as a ready-to-send letter."""
        records = "\n".join(f"  {i}. {r}" for i, r in enumerate(request.records_requested, 1))

        return f"""{requester_name}
{requester_address}

{request.generated_date}

{request.target_agency}
{request.target_address}

Re: {request.subject}

Dear FOIA Officer,

This is a request under the Freedom of Information Act (5 U.S.C. § 552) \
and any applicable state public records law.

I am requesting copies of the following records:

{records}

Date range: {request.date_range or "All available records"}

FEE WAIVER REQUEST: I request a waiver of all fees associated with this \
request. Disclosure of the requested information is in the public interest \
because it will contribute significantly to the public understanding of \
the environmental compliance history of this facility and its impact on \
the surrounding community. This information is not being requested for \
commercial purposes.

PREFERRED FORMAT: Please provide records in electronic format (PDF) \
via email to the extent possible.

If this request is denied in whole or in part, I ask that you justify \
all deletions or denials by reference to specific exemptions of the Act. \
I also expect you to release all segregable portions of otherwise exempt material.

I expect a response within the timeframe required by law. If you have \
questions about this request, please contact me at the address above.

Thank you for your prompt attention to this matter.

Sincerely,
{requester_name}

---
Request ID: {request.request_id}
Generated by Raíz environmental justice intelligence.
The roots see what the surface hides."""

    def mark_filed(self, request_id: str, filed_date: str = "") -> None:
        for r in self._requests:
            if r.request_id == request_id:
                r.status = "filed"
                r.filed_date = filed_date or datetime.now().strftime("%Y-%m-%d")
                break

    def check_overdue(self) -> list[FoiaRequest]:
        return [r for r in self._requests if r.is_overdue]

    def status_summary(self) -> str:
        if not self._requests:
            return "No FOIA requests tracked."

        parts = [f"FOIA Request Status ({len(self._requests)} tracked):"]
        for r in self._requests:
            status = r.status.upper()
            if r.is_overdue:
                status = "OVERDUE"
            days = r.days_until_deadline
            deadline_note = f" ({days} days remaining)" if days >= 0 else ""
            parts.append(
                f"  [{status}] {r.request_id}: {r.facility_name} → {r.target_agency}{deadline_note}"
            )

        overdue = self.check_overdue()
        if overdue:
            parts.append(f"\n  ⚠ {len(overdue)} request(s) OVERDUE — agency has not responded within legal timeframe")
            parts.append("  Consider filing an administrative appeal or contacting your representative")

        return "\n".join(parts)

    @property
    def requests(self) -> list[FoiaRequest]:
        return list(self._requests)
