"""Community Query Engine — one question, one answer.

"What is affecting my community?"

Enter a zip code. Get back everything Raíz knows:
  - Regulated facilities and their violation history
  - Toxic chemicals being released into your air and water
  - Current air quality from EPA monitors and community sensors
  - Whether there's a monitoring gap (no EPA monitor nearby)
  - Who owns the facilities and what they've disclosed to the SEC

This is the front door. Everything else is plumbing.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from raiz.sources.epa_echo import EchoSource, EchoReport
from raiz.sources.epa_tri import TriSource, CommunityToxicProfile
from raiz.sources.air_quality import (
    AirNowSource, PurpleAirSource, AirQualityReport, AirReading,
)
from raiz.sources.sec_edgar import SecEdgarSource, CorporateEnvironmentalProfile
from raiz.mapping.demographics import CensusSource, CommunityDemographics

logger = logging.getLogger(__name__)


@dataclass
class CommunityReport:
    """Everything Raíz knows about a community."""
    zip_code: str
    timestamp: datetime
    echo: EchoReport | None = None
    toxic_profile: CommunityToxicProfile | None = None
    air_quality: AirQualityReport | None = None
    demographics: CommunityDemographics | None = None
    corporate_profiles: list[CorporateEnvironmentalProfile] = field(default_factory=list)
    risk_score: float = 0.0
    risk_factors: list[str] = field(default_factory=list)

    def summarize(self) -> str:
        """Plain-language summary for community members."""
        parts = [
            f"Environmental Report for {self.zip_code}",
            f"Generated: {self.timestamp.strftime('%B %d, %Y at %I:%M %p UTC')}",
            "=" * 60,
        ]

        if self.echo:
            parts.append(f"\nREGULATED FACILITIES: {self.echo.total_facilities}")
            if self.echo.facilities_in_violation > 0:
                parts.append(
                    f"  {self.echo.facilities_in_violation} currently in violation "
                    f"({self.echo.total_violations_3yr} violations in last 3 years)"
                )
                if self.echo.total_penalties_3yr > 0:
                    parts.append(
                        f"  Total penalties assessed: ${self.echo.total_penalties_3yr:,.0f}"
                    )
                else:
                    parts.append(
                        "  No penalties assessed — violations without consequences"
                    )

            for f in self.echo.facilities[:5]:
                programs = ", ".join(f.programs) if f.programs else "unknown"
                parts.append(f"  - {f.name} ({programs})")
                if f.parent_company:
                    parts.append(f"    Owned by: {f.parent_company}")

        if self.toxic_profile:
            parts.append("")
            parts.append(self.toxic_profile.summarize())

        if self.air_quality:
            parts.append("")
            parts.append(self.air_quality.summarize())

        if self.demographics:
            parts.append("")
            parts.append(self.demographics.summarize())

        if self.corporate_profiles:
            parts.append("")
            parts.append("CORPORATE ACCOUNTABILITY:")
            for cp in self.corporate_profiles:
                parts.append(cp.summarize())

        if self.risk_factors:
            parts.append(f"\nRISK FACTORS ({self.risk_score:.1f}/10):")
            for rf in self.risk_factors:
                parts.append(f"  - {rf}")

        parts.append("")
        parts.append("This report was generated by Raíz (raíz = root).")
        parts.append("The roots see what the surface hides.")
        parts.append("Data sources: EPA ECHO, EPA TRI, AirNow, PurpleAir, US Census ACS, SEC EDGAR.")

        return "\n".join(parts)

    def action_items(self) -> list[str]:
        """Suggested actions for community members."""
        actions = []

        if self.echo and self.echo.facilities_in_violation > 0:
            actions.append(
                "Request inspection records for facilities in violation "
                "via FOIA (Freedom of Information Act)"
            )
            if self.echo.total_penalties_3yr == 0:
                actions.append(
                    "File a complaint with your state environmental agency — "
                    "violations without penalties means enforcement isn't happening"
                )

        if self.toxic_profile and self.toxic_profile.carcinogen_count > 0:
            actions.append(
                f"{self.toxic_profile.carcinogen_count} known carcinogens are being "
                "released in your area. Contact your state health department "
                "for community health screening information"
            )

        if self.air_quality and self.air_quality.monitoring_gap:
            actions.append(
                "Your community has an air quality monitoring gap. "
                "Consider requesting an EPA monitor placement or "
                "installing a PurpleAir community sensor (~$250)"
            )

        if not actions:
            actions.append(
                "No immediate action items identified. "
                "Stay informed by running this report periodically."
            )

        return actions


class CommunityQueryEngine:
    """The front door to Raíz.

    One method: query(zip_code). Returns everything.

    Args:
        airnow_key: AirNow API key (free from docs.airnowapi.org)
        purpleair_key: PurpleAir API key (free for research)
        dry_run: Use mock data instead of real APIs
    """

    def __init__(
        self,
        airnow_key: str = "",
        purpleair_key: str = "",
        census_key: str = "",
        dry_run: bool = False,
    ) -> None:
        self.echo = EchoSource(dry_run=dry_run)
        self.tri = TriSource(dry_run=dry_run)
        self.airnow = AirNowSource(api_key=airnow_key, dry_run=dry_run)
        self.purpleair = PurpleAirSource(api_key=purpleair_key, dry_run=dry_run)
        self.census = CensusSource(api_key=census_key, dry_run=dry_run)
        self.sec = SecEdgarSource(dry_run=dry_run)
        self._dry_run = dry_run

    async def query(self, zip_code: str) -> CommunityReport:
        """Query all data sources for a zip code.

        Returns a CommunityReport with everything Raíz knows.
        """
        now = datetime.now(timezone.utc)

        echo_report = await self.echo.community_report(zip_code)
        toxic_profile = await self.tri.community_profile(zip_code)
        airnow_readings = await self.airnow.current_by_zip(zip_code)

        pa_readings: list[AirReading] = []
        if echo_report.facilities:
            lat = echo_report.facilities[0].latitude
            lon = echo_report.facilities[0].longitude
            if lat and lon:
                pa_readings = await self.purpleair.sensors_near(lat, lon)

        nearest_epa = airnow_readings[0] if airnow_readings else None
        nearest_pa = pa_readings[0] if pa_readings else None
        monitoring_gap = (
            nearest_epa is None or nearest_epa.distance_miles > 5.0
        )

        air_report = AirQualityReport(
            zip_code=zip_code,
            timestamp=now,
            readings=airnow_readings + pa_readings,
            nearest_epa_monitor=nearest_epa,
            nearest_community_sensor=nearest_pa,
            monitoring_gap=monitoring_gap,
        )

        demographics = await self.census.get_demographics(zip_code)

        corporate_profiles = []
        seen_companies: set[str] = set()
        for f in echo_report.facilities[:10]:
            if f.parent_company and f.parent_company not in seen_companies:
                seen_companies.add(f.parent_company)
                profile = await self.sec.search_by_facility_owner(f.parent_company)
                if profile and profile.company:
                    corporate_profiles.append(profile)

        risk_score, risk_factors = self._assess_risk(
            echo_report, toxic_profile, air_report, demographics,
        )

        return CommunityReport(
            zip_code=zip_code,
            timestamp=now,
            echo=echo_report,
            toxic_profile=toxic_profile,
            air_quality=air_report,
            demographics=demographics,
            corporate_profiles=corporate_profiles,
            risk_score=risk_score,
            risk_factors=risk_factors,
        )

    def _assess_risk(
        self,
        echo: EchoReport,
        toxic: CommunityToxicProfile,
        air: AirQualityReport,
        demographics: CommunityDemographics | None = None,
    ) -> tuple[float, list[str]]:
        """Compute a community environmental risk score (0-10)."""
        score = 0.0
        factors = []

        if echo.facilities_in_violation > 0:
            score += min(3.0, echo.facilities_in_violation * 0.5)
            factors.append(
                f"{echo.facilities_in_violation} facilities currently in violation"
            )

        if echo.total_violations_3yr > 10:
            score += 1.0
            factors.append(
                f"{echo.total_violations_3yr} violations in last 3 years"
            )

        if echo.total_penalties_3yr == 0 and echo.total_violations_3yr > 0:
            score += 1.5
            factors.append(
                "Violations with zero penalties — enforcement gap"
            )

        if toxic.carcinogen_count > 0:
            score += min(2.0, toxic.carcinogen_count * 0.5)
            factors.append(
                f"{toxic.carcinogen_count} carcinogenic chemicals being released"
            )

        if toxic.total_air_lbs > 50000:
            score += 1.0
            factors.append(
                f"{toxic.total_air_lbs:,.0f} lbs of toxic chemicals released into air"
            )

        if air.monitoring_gap:
            score += 1.0
            factors.append(
                "Air quality monitoring gap — no EPA monitor nearby"
            )

        unhealthy = [r for r in air.readings if r.is_unhealthy]
        if unhealthy:
            score += 1.0
            factors.append(
                f"Current air quality at Unhealthy levels ({unhealthy[0].aqi} AQI)"
            )

        if demographics:
            if demographics.majority_minority:
                score += 1.0
                poc_pct = 100 - demographics.pct_white
                factors.append(
                    f"Majority-minority community ({poc_pct:.0f}% people of color)"
                )
            if demographics.low_income:
                score += 0.5
                factors.append(
                    f"Low-income community (median income ${demographics.median_household_income:,.0f})"
                )
            if demographics.pct_under_5 > 8:
                score += 0.5
                factors.append(
                    f"High child population ({demographics.pct_under_5:.0f}% under 5) — children are most vulnerable to pollution"
                )

        return min(10.0, score), factors
